---
# SSH user, this user should allow ssh based auth without requiring a password
ansible_ssh_user: ec2-user

# If ansible_ssh_user is not root, ansible_become must be set to true
ansible_become: true
deployment_type: openshift-enterprise

openshift_master_identity_providers: [{'name': 'htpasswd_auth', 'login': 'true', 'challenge': 'true', 'kind': 'HTPasswdPasswordIdentityProvider', 'filename': '/etc/origin/master/htpasswd'}]
openshift_master_htpasswd_users: { '{{ rh_user }}': '{{ pass_output.stdout }}' } # {{ rh_pass }}

openshift_registry_selector: 'type=infra'
openshift_hosted_router_selector: 'type=infra'
openshift_cloudprovider_kind: aws
openshift_cloudprovider_aws_access_key: {{ ansible_env['AWS_ACCESS_KEY'] }}
openshift_cloudprovider_aws_secret_key: {{ ansible_env['AWS_SECRET_KEY'] }}